-   first let's load the data
-   then compute proportion frequency

```{r}
#df <- read.csv("cnk_data.csv")
df <- read.csv("cnk_data_slouceno.csv")

df$proportion_freq <- as.numeric(df$proportion_freq)
df$proportion_freq <- df$negated.imperative/df$absolute_frequency

library(ggplot2)
library(dplyr)

p <- df %>%
  ggplot( aes(x = negated.imperative, fill = aspect)) +
  geom_histogram(position = 'identity', binwidth = 150)
p

p2 <- df %>%
  ggplot( aes(x = proportion_freq, fill = aspect)) +
  geom_histogram(position = 'identity')
p2


t.test(df$proportion_freq[df$aspect == "imperfective"], df$proportion_freq[df$aspect == "perfective"])

t.test(df$negated.imperative[df$aspect == "imperfective"], df$negated.imperative[df$aspect == "perfective"])
```

- Bayesian version below (can crash on some data)
- first for the non-proportional data

```{r, eval = TRUE}
library(BEST)
library(BayesFactor)

bayesTtest <- BESTmcmc(df$negated.imperative[df$aspect == "imperfective"], df$negated.imperative[df$aspect == "perfective"])

bayesTtest
#mcmcOut <- posterior(bayesTtest,iterations=10000)

plot(bayesTtest)

summary(bayesTtest)
```

- now for the proportional data

```{r}

bayesTtestProp <- BESTmcmc(df$proportion_freq[df$aspect == "imperfective"], df$proportion_freq[df$aspect == "perfective"])

summary(bayesTtestProp)

plot(bayesTtestProp)

bayesTtest
bayesTtestProp
```

